# Generated by Django 4.1.5 on 2023-01-20 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=120)),
                ('last_name', models.CharField(max_length=120)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('average_movie_reate', models.FloatField(blank=True, null=True)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Actors',
                'verbose_name_plural': 'Actors',
            },
        ),
    ]
